// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDefaultPath() {
  return window['go']['main']['App']['GetDefaultPath']();
}

export function RunExport(arg1, arg2, arg3) {
  return window['go']['main']['App']['RunExport'](arg1, arg2, arg3);
}
