// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDefaultPath():Promise<string>;

export function RunExport(arg1:string,arg2:string,arg3:string):Promise<string>;
